-- 1. Obliterate all data gracefully
DO $$ DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = current_schema()) LOOP
        EXECUTE 'TRUNCATE TABLE ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END $$;

-- 2. Restore System Foundations (Singleton SaaS & Base Services)
INSERT INTO saas_config (id, app_name_ar, app_name_en, app_slogan_ar, app_slogan_en, primary_color, language)
VALUES ('SINGLETON', 'GCM Testing', 'GCM ERP Test Suite', 'بيئة اختبارات معزولة', 'Isolated Testing Sandbox', '#dc2626', 'en');

INSERT INTO services (service_id, service_name, service_description) VALUES 
('SERV-GEN-01', 'General Waste', 'Standard non-hazardous waste collection'),
('SERV-HAZ-02', 'Hazardous Waste', 'Regulated hazardous material transport'),
('SERV-REC-03', 'Recyclables', 'Metal, Plastic, and Paper recycling services');

-- 3. Inject the 11 Primary Core Users (Password: 123)
-- Hash generated by bcrypt: $2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.
INSERT INTO users (id, name, email, password, role, status) VALUES
('USER-ADMIN', 'System Admin', 'admin@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'ADMIN', 'ACTIVE'),
('USER-BASIC', 'Basic User', 'user@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'USER', 'ACTIVE'),
('USER-CLIENT', 'Client Employee', 'client.emp@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'COMPANY_USER', 'ACTIVE'),
('USER-PROJ', 'Project Supervisor', 'site.supervisor@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'PROJECT_USER', 'ACTIVE'),
('USER-ACCT', 'Accountant', 'accountant@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'ACCOUNTANT', 'ACTIVE'),
('USER-DATA', 'Data Entry', 'data.entry@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'DATA_ENTRY', 'ACTIVE'),
('USER-REP', 'Reports Manager', 'reports@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'REPORTS_MANAGER', 'ACTIVE'),
('USER-LOG', 'Fleet Logistics', 'logistics@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'LOGISTICS', 'ACTIVE'),
('USER-DRV', 'Field Driver', 'driver@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'DRIVER', 'ACTIVE'),
('USER-PORTAL', 'Client Portal', 'client.portal@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'CLIENT', 'ACTIVE'),
('USER-SUB', 'Subcontractor', 'subcontractor@gcm.local', '$2b$10$8VYj2ignUUlyVbiihTOihuqi3NDDJQtVumSLFSd9prBFim9Hm8Fh.', 'SUBCONTRACTOR', 'ACTIVE');
